# Generated by Django 4.1.1 on 2022-11-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_user',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='sirname',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
