# Generated by Django 4.1.1 on 2022-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('num_house', models.IntegerField()),
                ('num_kor', models.IntegerField()),
                ('district', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('text_info', models.TextField(max_length=10)),
                ('id_object', models.CharField(max_length=10)),
                ('author_object', models.CharField(max_length=10)),
                ('rooms', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('square', models.FloatField()),
                ('plan', models.CharField(max_length=10)),
            ],
        ),
    ]
