# Generated by Django 4.1.1 on 2022-11-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flats',
            name='id_object',
        ),
        migrations.AlterField(
            model_name='flats',
            name='author_object',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flats',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flats',
            name='district',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flats',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='floors',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='num_house',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='num_kor',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='flats',
            name='plan',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flats',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='rooms',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='square',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='street',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flats',
            name='text_info',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='flats',
            name='types',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
