# Generated by Django 4.1.1 on 2022-11-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0003_flat_delete_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='num_house',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='num_kor',
        ),
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(choices=[(0, 'Харьков'), (1, 'Никополь')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(choices=[(0, 'ГСВ'), (1, 'Северный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(choices=[('улучшенка', 'улучшенка'), (1, 'обычная')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(choices=[(0, 'пр. Гагарина'), (1, 'пер. Спокойный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='text_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='types',
            field=models.CharField(choices=[(0, 'Квартира')], max_length=10),
        ),
    ]
