# Generated by Django 4.1.1 on 2022-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0004_remove_flat_num_house_remove_flat_num_kor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(choices=[('0', 'Харьков'), ('1', 'Никополь')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(choices=[('0', 'ГСВ'), ('1', 'Северный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(choices=[('0', 'улучшенка'), ('1', 'обычная')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(choices=[('0', 'пр. Гагарина'), ('1', 'пер. Спокойный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='text_info',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='flat',
            name='types',
            field=models.CharField(choices=[('0', 'Квартира')], max_length=10),
        ),
    ]
