# Generated by Django 4.1.1 on 2022-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0005_alter_flat_city_alter_flat_district_alter_flat_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.IntegerField(choices=[(0, 'ГСВ'), (1, 'Северный')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='types',
            field=models.CharField(choices=[('Квартира', 'Квартира')], max_length=10),
        ),
    ]
