# Generated by Django 4.1.1 on 2022-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0006_alter_flat_city_alter_flat_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.IntegerField(choices=[(0, 'ГСВ'), (1, 'Северный')]),
        ),
    ]
