# Generated by Django 4.1.1 on 2022-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0007_alter_flat_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(choices=[('Северный', 'ГСВ'), ('Северный', 'Северный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(choices=[('улучшенка', 'улучшенка'), ('обычная', 'обычная')], max_length=30),
        ),
    ]
