# Generated by Django 4.1.1 on 2022-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0008_alter_flat_district_alter_flat_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floors',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='plan',
            field=models.CharField(blank=True, choices=[('улучшенка', 'улучшенка'), ('обычная', 'обычная')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.FloatField(blank=True),
        ),
    ]
