# Generated by Django 4.1.1 on 2022-11-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0009_alter_flat_floor_alter_flat_floors_alter_flat_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
