# Generated by Django 4.1.1 on 2022-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0011_alter_flat_city_alter_flat_district_alter_flat_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Квартира', 'Квартира')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price', models.FloatField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('text_info', models.TextField(blank=True, max_length=300)),
                ('author_object', models.CharField(blank=True, max_length=10)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('square', models.FloatField(blank=True, null=True)),
                ('land_part', models.FloatField(blank=True, null=True)),
                ('land_square', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Часть дома', 'Часть дома'), ('Гостинка', 'Гостинка')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('rooms_min', models.IntegerField(blank=True, null=True)),
                ('rooms_max', models.IntegerField(blank=True, null=True)),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('floors_min', models.IntegerField(blank=True, null=True)),
                ('floors_max', models.IntegerField(blank=True, null=True)),
                ('square_min', models.FloatField(blank=True, null=True)),
                ('square_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30),
        ),
    ]
