# Generated by Django 4.1.1 on 2022-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0012_house_searchobject_alter_flat_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Квартира', 'Квартира')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('rooms_min', models.IntegerField(blank=True, null=True)),
                ('rooms_max', models.IntegerField(blank=True, null=True)),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('floors_min', models.IntegerField(blank=True, null=True)),
                ('floors_max', models.IntegerField(blank=True, null=True)),
                ('square_min', models.FloatField(blank=True, null=True)),
                ('square_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Дом', 'Дом'), ('Часть дома', 'Часть дома')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('rooms_min', models.IntegerField(blank=True, null=True)),
                ('rooms_max', models.IntegerField(blank=True, null=True)),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('land_part_min', models.FloatField(blank=True, null=True)),
                ('land_part_max', models.FloatField(blank=True, null=True)),
                ('land_square_min', models.FloatField(blank=True, null=True)),
                ('land_square_max', models.FloatField(blank=True, null=True)),
                ('square_min', models.FloatField(blank=True, null=True)),
                ('square_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSmartFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Квартира', 'Квартира'), ('Часть', 'Часть')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price_min', models.FloatField(blank=True, null=True)),
                ('price_max', models.FloatField(blank=True, null=True)),
                ('date_begin', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('rooms_min', models.IntegerField(blank=True, null=True)),
                ('rooms_max', models.IntegerField(blank=True, null=True)),
                ('floor_min', models.IntegerField(blank=True, null=True)),
                ('floor_max', models.IntegerField(blank=True, null=True)),
                ('floors_min', models.IntegerField(blank=True, null=True)),
                ('floors_max', models.IntegerField(blank=True, null=True)),
                ('square_min', models.FloatField(blank=True, null=True)),
                ('square_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Smartflat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(choices=[('Квартира', 'Квартира'), ('Часть', 'Часть')], max_length=10)),
                ('city', models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Никополь', 'Никополь')], max_length=20)),
                ('street', models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30)),
                ('district', models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный')], max_length=30)),
                ('price', models.FloatField(blank=True, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('text_info', models.TextField(blank=True, max_length=300)),
                ('author_object', models.CharField(blank=True, max_length=10)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('floors', models.IntegerField(blank=True, null=True)),
                ('square', models.FloatField(blank=True, null=True)),
                ('part', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SearchObject',
        ),
        migrations.AlterField(
            model_name='house',
            name='types',
            field=models.CharField(choices=[('Дом', 'Дом'), ('Часть дома', 'Часть дома')], max_length=10),
        ),
    ]
