# Generated by Django 4.1.1 on 2022-11-16 10:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0013_searchflat_searchhouse_searchsmartflat_smartflat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Северный', 'Северный'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
    ]
