# Generated by Django 4.1.1 on 2022-11-16 10:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0014_alter_flat_street_alter_searchsmartflat_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30),
        ),
    ]
