# Generated by Django 4.1.1 on 2022-11-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0017_alter_searchflat_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=models.CharField(blank=True, choices=[('пр. Гагарина', 'пр. Гагарина'), ('пер. Спокойный', 'пер. Спокойный')], max_length=30),
        ),
    ]
