# Generated by Django 4.1.1 on 2022-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0019_city_district_streer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streer',
            new_name='Street',
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
