# Generated by Django 4.1.1 on 2022-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0020_rename_streer_street_alter_city_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
    ]
