# Generated by Django 4.1.1 on 2022-11-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0021_alter_flat_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='city',
            field=models.CharField(blank=True, choices=[('Харьков', 'Харьков'), ('Чугуев', 'Чугуев')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('Салтовка', 'Салтовка'), ('ГСВ', 'ГСВ')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('ул. Сумская', 'ул. Сумская'), ('ул. Омская', 'ул. Омская'), ('проспект Науки', 'проспект Науки')], max_length=30),
        ),
    ]
