# Generated by Django 4.1.1 on 2022-11-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0022_alter_flat_district_alter_flat_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchflat',
            name='street_s',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='district',
            field=models.CharField(choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], default=('Салтовка', 'Салтовка'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=models.CharField(choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='district',
            field=models.CharField(choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], default=('Салтовка', 'Салтовка'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='street',
            field=models.CharField(choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='street',
            field=models.CharField(choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], max_length=30),
        ),
    ]
