# Generated by Django 4.1.1 on 2022-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0023_searchflat_street_s_alter_flat_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchflat',
            name='street_s',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
