# Generated by Django 4.1.1 on 2022-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0026_alter_searchflat_district_alter_searchflat_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=300),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
    ]
