# Generated by Django 4.1.1 on 2022-11-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0027_alter_searchflat_district_alter_searchflat_street_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=300),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], default=('Салтовка', 'Салтовка'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchhouse',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='searchsmartflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], default=('проспект Гагарина', 'проспект Гагарина'), max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='district',
            field=models.CharField(blank=True, choices=[('ГСВ', 'ГСВ'), ('Новые Дома', 'Новые Дома'), ('Салтовка', 'Салтовка')], max_length=30),
        ),
        migrations.AlterField(
            model_name='smartflat',
            name='street',
            field=models.CharField(blank=True, choices=[('проспект Гагарина', 'проспект Гагарина'), ('проспект Героев Сталинграда', 'проспект Героев Сталинграда'), ('проспект Науки', 'проспект Науки'), ('ул. Омская', 'ул. Омская'), ('ул. Сумская', 'ул. Сумская'), ('ул. Харьковских Дивизий', 'ул. Харьковских Дивизий')], max_length=30),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
