# Generated by Django 4.1.1 on 2022-11-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0030_alter_flat_options_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
