# Generated by Django 4.1.1 on 2022-12-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0033_alter_searchflat_city_alter_searchflat_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='images',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
