# Generated by Django 4.1.1 on 2022-12-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0037_alter_flat_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-add_date']},
        ),
        migrations.AlterModelOptions(
            name='smartflat',
            options={'ordering': ['-add_date']},
        ),
        migrations.CreateModel(
            name='FlatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoes', models.ImageField(blank=True, upload_to='flats/pics')),
                ('flat_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FlatPhoto', to='estate_objects.flat')),
            ],
        ),
    ]
