# Generated by Django 4.1.1 on 2022-12-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0038_alter_house_options_alter_smartflat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flatphoto',
            old_name='flat_photo',
            new_name='flat',
        ),
    ]
