# Generated by Django 4.1.1 on 2022-12-30 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0039_rename_flat_photo_flatphoto_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.ImageField(blank=True, null=True, upload_to='flats/pics')),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flat',
            name='images',
        ),
        migrations.DeleteModel(
            name='FlatPhoto',
        ),
        migrations.AddField(
            model_name='flatimage',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat_image', to='estate_objects.flat'),
        ),
    ]
