# Generated by Django 4.1.1 on 2023-01-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0040_flatimage_remove_flat_images_delete_flatphoto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimage',
            name='image_data',
            field=models.ImageField(default='default.jpg', upload_to='flats/pics'),
        ),
    ]
