# Generated by Django 4.1.1 on 2023-03-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_objects', '0041_alter_flatimage_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatimage',
            name='image_data',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='flats/pics'),
        ),
    ]
