from django.urls import path

from .views import *

urlpatterns = [
    path('', main_menu, name='main_menu_url'),
    path('author/<str:author_object>', Objects_for_author.as_view(), name='objects_for_author_url'),
    path('author/<str:author_object>', Objects_for_phone_number.as_view(), name='objects_for_phone_number_url'),
    path('search/', search_for_phone_number, name='search_for_phone_number_url'),
    path('author/profile/<str:author_object>', User_profile.as_view(), name='user_profile_url'),
    path('data/', main_data_menu, name='main_data_menu_url'),
    path('data/city/create/', CityCreate.as_view(),name='city_create_url'),
    path('data/city/<int:city_id>/update/',CityUpdate.as_view(), name='city_update_url'),
    path('data/city/<int:city_id>/delete/',CityDelete.as_view(), name='city_delete_url'),
    path('data/city/<int:city_id>/detail/',CityDetailView.as_view(), name='city_detail_url'),
    path('data/city/', city_list, name='cities_list_url'),
    path('data/street/create/', StreetCreate.as_view(),name='street_create_url'),
    path('data/street/<int:street_id>/update/',StreetUpdate.as_view(), name='street_update_url'),
    path('data/street/<int:street_id>/delete/',StreetDelete.as_view(), name='street_delete_url'),
    path('data/street/<int:street_id>/detail/',StreetDetailView.as_view(), name='street_detail_url'),
    path('data/street/', street_list, name='streets_list_url'),
    path('data/district/create/', DistrictCreate.as_view(),name='district_create_url'),
    path('data/district/<int:district_id>/update/',DistrictUpdate.as_view(), name='district_update_url'),
    path('data/district/<int:district_id>/delete/',DistrictDelete.as_view(), name='district_delete_url'),
    path('data/district/<int:district_id>/detail/',DistrictDetailView.as_view(), name='district_detail_url'),
    path('data/district/', district_list, name='districts_list_url'),
    path('data/users/', users_list, name='users_list_url'),
    path('flats/', flats_list, name='flats_list_url'),
    path('flats/<int:flat_id>/',FlatDetailView.as_view(), name='flat_detail_url'),
    path('flats/<int:flat_id>/big_image/',view_big_image, name='flat_big_image_url'),
    path('flats/<int:flat_id>/update/<int:flatimage_id>/',delete_image, name='image_delete_url'),
    path('flats/create/', FlatCreate.as_view(),name='flat_create_url'),
    path('flats/search/', SearchFlat.as_view(),name='search_flat_url'),
    path('flats/<int:flat_id>/update/',FlatUpdate.as_view(), name='flat_update_url'),
    path('flats/<int:flat_id>/delete/',FlatDelete.as_view(), name='flat_delete_url'),
    path('houses/', houses_list, name='houses_list_url'),
    path('houses/<int:house_id>/',HouseDetailView.as_view(), name='house_detail_url'),
    path('houses/create/', HouseCreate.as_view(),name='house_create_url'),
    path('houses/search/', SearchHouse.as_view(),name='search_house_url'),
    path('houses/<int:house_id>/update/',HouseUpdate.as_view(), name='house_update_url'),
    path('houses/<int:house_id>/delete/',HouseDelete.as_view(), name='house_delete_url'),
    path('smartflats/', smart_flats_list, name='smart_flats_list_url'),
    path('smartflats/<int:smartflat_id>/',SmartflatDetailView.as_view(), name='smart_flat_detail_url'),
    path('smartflats/create/', SmartflatCreate.as_view(),name='smart_flat_create_url'),
    path('smartflats/search/', SearchSmartflat.as_view(),name='search_smart_flat_url'),
    path('smartflats/<int:smartflat_id>/update/',SmartflatUpdate.as_view(), name='smart_flat_update_url'),
    path('smartflats/<int:smartflat_id>/delete/',SmartflatDelete.as_view(), name='smart_flat_delete_url'),
]

